version: "3.1"

services:
  node-exporter:
    image: prom/node-exporter
    networks:
      - monitoring
    volumes:
      - /:/rootfs
      - /sys:/host/sys
      - /proc:/host/proc
    deploy:
      mode: global
    labels:
      container-type: "monitoring"
    command: -collector.procfs /host/proc -collector.sysfs /host/sys --collector.textfile.directory /rootfs/tmp/prometheus

networks:
    monitoring:
      external:
        name: monitoring